### ISSUE TITLE
Applied Energistics 2

### ISSUE THREAD

**Issue by Roigen** [AlmuraDev/Almura#208] opened 2015-11-15 17:05 UTC
Please add AE2 because it´s really good storage mod. I don´t know if you know it, but it´s not hard. I hope it haven´t got lots of bugs, but i think no. Thanks for reading :)

**Comment by gabizou** [comment] 2015-11-15 18:22
Duplicate of #85.

**Closed by gabizou** 2015-11-15 18:22 UTC
